/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PracticasEnClase.ClienteRest;
import kong.unirest.*;
import kong.unirest.json.JSONObject;
import java.util.Scanner;
import java.io.IOException;
import java.io.BufferedReader;
import java.io.InputStreamReader;


public class App {


    public static void main(String[] args) throws IOException{
        

     HttpResponse<JsonNode> ListadoEstudiantes = Unirest.get("http://localhost:7000/api/estudiante")
     .header("accept", "application/json")
     .asJson();

    System.out.println("Inciso No. 1 ==> Listar Todos los estudiantes: \n"+ListadoEstudiantes.getBody()+"\n");

    System.out.println("\n========================================\n");


    //======================================================================================
    System.out.println("Consultar Estudiante. \n");

   
   
    System.out.println("Inserte matricula a consultar: ");
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); 
    Scanner in = new Scanner(System.in);
    String matEst = in.nextLine();
    
   

    HttpResponse<JsonNode> consultaEstudiante = Unirest.get("http://localhost:7000/api/estudiante/"+matEst)
    .header("accept", "application/json")
    .asJson();

    
    System.out.println("El estudiante consultado es: \n"+consultaEstudiante.getBody());
    System.out.println("\n");


   
     //======================================================================================
     System.out.println("\n========================================\n");
     System.out.println("Crear Estudiante. \n");

     JSONObject crear = new JSONObject();

     System.out.println("Inserte Matricula: ");

     String matEst1 = br.readLine();
     crear.put("matricula",matEst1);
     System.out.println("\nNombre: ");
     String nombre = br.readLine();
     crear.put("nombre",nombre);
     System.out.println("\nCarrera: ");
     String carrera = br.readLine();
     crear.put("carrera",carrera);

     HttpResponse agregarEstudiante = Unirest.post("http://localhost:7000/api/estudiante/")
     .header("accept", "application/json")
     .header("Content-Type", "application/json")
     .body(crear)
     .asJson();
   





  //======================================================================================
  System.out.println("\n========================================\n");
    System.out.println("Eliminar un estudiante. \n");
     System.out.println("\n Inserte matricula de estudiante a eliminar: \n");
     String eliminarEst = br.readLine();

     HttpResponse eliminarEstudiante = Unirest.delete("http://localhost:7000/api/estudiante/" + eliminarEst).asEmpty();

     System.out.println("\nEstudiante eliminado" );


    }
}
